# SwiftLint Configuration for Beaver Logging Framework
# This configuration is tailored for a Swift logging framework with focus on
# code quality, documentation, and consistency.

# Include all Swift files in the project
included:
  - Beaver/
  - BeaverTests/
  - Examples/

# Exclude generated files and dependencies
excluded:
  - Beaver.xcodeproj/
  - .build/
  - Pods/
  - Carthage/
  - Package.resolved
  - .swiftpm/

# Analyzer rules (require building the project)
analyzer_rules:
  - unused_import
  - unused_declaration

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  - missing_docs

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments for development
  - file_header # Disable file header requirement for now

# Custom rule configurations
line_length:
  warning: 120
  error: 140
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 200
  error: 300

file_length:
  warning: 400
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - ID
    - url
    - URL
    - db
    - DB
    - api
    - API
    - ui
    - UI
    - os
    - OS

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - ID
    - URL
    - API
    - UI
    - OS
    - DB

# Documentation requirements
missing_docs:
  warning: open
  error: public

# Multiline parameters configuration
multiline_parameters:
  allows_single_line: true

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: false

# Custom rules for logging framework
custom_rules:
  # Encourage use of log levels (but allow print in test files)
  proper_log_levels:
    name: "Use Proper Log Levels"
    regex: 'print\s*\('
    message: "Use proper logging instead of print() statements"
    severity: warning
    excluded: ".*Tests/.*"

# Reporter configuration
reporter: "xcode"
